apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
spec:
<<<<<<< HEAD
  replicas: 50
=======
  replicas: 4
>>>>>>> a9abc94e6c9e3190709eb612884720bdebfa9cf1
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
        - name: api
          image: vajo/k8s-demo-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
