apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-reader
rules:
- apiGroups: [""] # The empty string "" refers to the core Kubernetes API group
  resources: ["pods", "nodes", "namespaces", "services", "deployments", "replicasets", "pods/logs", "pods/exec"]
  verbs: ["all"]